import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import "../App.css";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet";
const Disclaimer = () => {
  return (
    <>
      <Helmet>
        <title>Read Our Disclaimer | SLOC - Search Land of Choice</title>
        <meta
          property="og:title"
          content="Read Our Disclaimer | SLOC - Search Land of Choice"
        />
        <meta
          property="og:description"
          content="Read the Disclaimer for SLOC, your trusted real estate partner. Learn about the terms, conditions, and legal information related to our property services and offerings."
        />
      </Helmet>
      <section className="disclamer baner-iner">
        <Container className="">
          <Row className="align-items-center">
            <Col md={12} className="animate__animated animate__fadeInLeft">
              <h2 className="fw-bold blog-h mt-2">Disclaimer</h2>
              <p className=" blog-p">
                Transparency matters! Here's everything you{" "}
                <span className="bl-full">
                  need to know before you proceed.
                </span>
              </p>
            </Col>
          </Row>
        </Container>
      </section>
      <section className="blog-text btm-space">
        <Container fluid className="">
          <Row className=" justify-content-center">
            <Col md={10} className="all-border">
              <p>
                The content provided on this website is for information purposes
                only and does not constitute an offer to avail any service. The
                prices mentioned are subject to change without prior notice, and
                the availability of the properties mentioned is not guaranteed.
              </p>
              <br />
              <p>
                Users of this website are hereby advised to exercise due
                diligence and to independently validate and verify all
                information about any property/project before deciding to
                purchase the same or taking any other action. The images
                displayed on the website are for representation purposes only
                and may not reflect the actual properties accurately.
              </p>
              <br />
              <p>
                Please note that this is the official website of an authorized
                marketing partner. The content, design, and information on this
                website are protected by copyright and other intellectual
                property rights. Any unauthorized use or reproduction of the
                content may violate applicable laws. All trademarks are the
                property of their respective owners.
              </p>
              <br />
              <p>
                The EMI Calculator provided on this website is for informational
                and illustrative purposes only. The results generated by the
                calculator are estimates based on the information you provide
                and may not reflect the actual EMI, interest rate, or loan terms
                offered by financial institutions. Actual loan offers may vary
                depending on various factors including your credit score, loan
                eligibility, and the policies of individual lenders. We do not
                guarantee the accuracy, reliability, or suitability of the
                results for your specific financial situation. Please consult
                with a financial advisor or lending institution before making
                any financial decisions.
              </p>
            </Col>
          </Row>
        </Container>
      </section>
    </>
  );
};
export default Disclaimer;
